spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookexplorer

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: book-explorer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.bookexplorer.kafka"

  quartz:
    job-store-type: memory
    properties:
      org.quartz.threadPool.threadCount: 1

app:
  subjects: fantasy,science,history

server:
  port: 8080

logging:
  level:
    com.example.bookexplorer: DEBUG
